---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test-kustomization
  namespace: flux-system
spec:
  interval: 5s
  path: ./clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: test
  validation: client

