---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: test
  namespace: flux-system
spec:
  interval: 3s
  ref:
    branch: integration_tests
  secretRef:
    name: test-auth
  url: ssh://git@github.com/EnterpriseDB/upm-substrate.git

